project 'SampleApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleApp
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'SKYLINK', :git => 'https://github.com/Temasys/SKYLINK-iOS.git'

end
