project 'SampleApp.xcodeproj'

platform :ios, '9.0'

target 'SampleApp' do
  use_frameworks!


pod 'SKYLINK', :git => 'https://github.com/Temasys/SKYLINK-iOS.git', :branch => 'test'
pod 'WebRTC', :git => 'https://github.com/lyx501135/WebRTC.git'

end
